import { notFound } from "next/navigation";

export const metadata = {
  title: `${"product"}`,
  description: "Generated by create next app",
};
const Page = async ({ params }) => {
  const { id } = await params;

  if (isNaN(id) || id > 100 || id < 1) {
    return notFound();
  }

  return <>id : {id} </>;
};

export default Page;
