import { notFound } from "next/navigation";
export const metadata = {
  title: `${"product"}`,
  description: "Generated by create next app",
};

const Page = async (prop) => {
  const { id } = await prop.params;

  if (id > 100) {
    return notFound();
  }

  return <>id : {id} </>;
};

export default Page;
