import SearchParamButton from "@/Components/S1/Button/SearchParamButton";
import Link from "next/link";
import Posts from "./_Posts/page";

export const metadata = {
  title: {
    default: "Session 1",
  },
  description: "Generated by create next app",
};

const S1 = () => {
  const id = [];
  for (let i = 0; i <= 100; i++) {
    id.push(i);
  }

  // Meta data

  // dynamic route

  // hidden page

  // groups route

  // layouts

  // navlink - use client - usePathname

  // use Router

  // useSearchParam

  // template

  // cath all segment

  // loading ui

  // error page
  return (
    <>
      <h1>Dynamic Route</h1>
      <ul>
        {id?.map((item, index) => {
          return (
            <li key={index} className="inline-block mx-10">
              <Link href={`/S1/${item}`}>{item}</Link>
            </li>
          );
        })}
      </ul>
      <h1>Groups Route</h1>
      <ul className="flex flex-row gap-10">
        <li>
          <Link href={"/S1/login"}>login</Link>
        </li>
        <li>
          <Link href={"/S1/register"}>register</Link>
        </li>
      </ul>
      <SearchParamButton />
      <div className="flex flex-row flex-wrap justify-center items-center">
        <Posts />
      </div>
    </>
  );
};

export default S1;
