import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../Components/S1/Header/Header";
import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapImp from "@/Components/S2/BootstrapImp/BootstrapImp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Next 15",
    template: "%s | Next 15",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <BootstrapImp />
      </body>
    </html>
  );
}
