import "./globals.css";
import Header from "../Components/S1/Header/Header";
import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapImp from "@/Components/S2/BootstrapImp/BootstrapImp";

export const metadata = {
  title: {
    default: "Next 15",
    template: "%s | Next 15",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <BootstrapImp />
      </body>
    </html>
  );
}
